Repository pagopa/interop-be-monorepo, pull requests merged in 2024-10, with the labels that each got.

#1009 IMN-736 - pt 1 - API GW Agreement errors without passthrough / bubble-up
  packages/api-clients/src/axiosLogInterceptors.ts
  packages/api-gateway/src/api/agreementApiConverter.ts
  packages/api-gateway/src/clients/catchClientError.ts
  packages/api-gateway/src/models/errors.ts
  packages/api-gateway/src/routers/apiGatewayRouter.ts
  packages/api-gateway/src/services/agreementService.ts
  packages/api-gateway/src/services/purposeService.ts
  packages/api-gateway/src/services/validators.ts
  packages/api-gateway/src/utilities/errorMappers.ts
  packages/models/src/errors.ts
Labels: api-gateway

#1048 IMN-865 - Fixing descriptor attributes conversion in BFF
  packages/backend-for-frontend/src/api/catalogApiConverter.ts
Labels: bff

#1052 IMN-869: removed contentType' checks on download
  packages/backend-for-frontend/src/model/errors.ts
  packages/backend-for-frontend/src/routers/agreementRouter.ts
  packages/backend-for-frontend/src/services/agreementService.ts
  packages/backend-for-frontend/src/services/purposeService.ts
  packages/backend-for-frontend/src/utilities/errorMappers.ts
  packages/backend-for-frontend/src/utilities/mimeTypes.ts
Labels: bff

#1041 IMN-851 - Removing with attributes models and converters
  packages/agreement-lifecycle/src/filters/attributesFilter.ts
  packages/agreement-lifecycle/src/index.ts
  packages/agreement-lifecycle/src/models/models.ts
  packages/agreement-lifecycle/src/validator/attributesValidator.ts
  packages/agreement-process/src/model/domain/agreement-validators.ts
  packages/agreement-process/src/services/agreementService.ts
  packages/agreement-process/src/services/agreementStateProcessor.ts
  packages/backend-for-frontend/src/api/catalogApiConverter.ts
  packages/backend-for-frontend/src/api/tenantApiConverter.ts
  packages/backend-for-frontend/src/services/validators.ts
Labels: bff

#937 IMN-796 Add scaffold for catalog-platformstate-writer
  docker/docker-compose.yml
  docker/dynamo-db/schema/platform-states.json
  docker/dynamo-db/schema/token-generation-states.json
  package.json
  packages/catalog-platformstate-writer/.env
  packages/catalog-platformstate-writer/Dockerfile
  packages/catalog-platformstate-writer/aws.config.local
  packages/catalog-platformstate-writer/package.json
  packages/catalog-platformstate-writer/src/config/config.ts
  packages/catalog-platformstate-writer/src/consumerServiceV1.ts
  packages/catalog-platformstate-writer/src/consumerServiceV2.ts
  packages/catalog-platformstate-writer/src/index.ts
  packages/catalog-platformstate-writer/src/utils.ts
  packages/catalog-platformstate-writer/test/sample.test.ts
  packages/catalog-platformstate-writer/test/tsconfig.json
  packages/catalog-platformstate-writer/test/utils.ts
  packages/catalog-platformstate-writer/test/vitestGlobalSetup.ts
  packages/catalog-platformstate-writer/tsconfig.check.json
  packages/catalog-platformstate-writer/tsconfig.json
  packages/catalog-platformstate-writer/vitest.config.ts
  packages/catalog-readmodel-writer/test/catalogReadmodelWriter.integration.test.ts
  packages/commons-test/src/containerTestUtils.ts
  packages/commons-test/src/index.ts
  packages/commons-test/src/protobufConvertersToV1/catalogProtobufConverterToV1.ts
  packages/commons-test/src/setupTestContainersVitestGlobal.ts
  packages/commons/src/config/consumerServiceConfig.ts
  packages/commons/src/config/index.ts
  packages/commons/src/config/tokenGenerationReadmodelDbConfig.ts
  packages/models/src/brandedIds.ts
  packages/models/src/index.ts
  packages/models/src/token-generation-readmodel/dynamoDB-keys.ts
  packages/models/src/token-generation-readmodel/platform-states-entry.ts
  packages/models/src/token-generation-readmodel/token-generation-states-entry.ts
  pnpm-lock.yaml
Labels: authorization-server

#1057 IMN-873 - samlLoginCallback 400 error - fixing urlencoded body parsing
  packages/backend-for-frontend/src/app.ts
Labels: bff

#1054 IMN-867 - Fix BFF getProducerPurposes by adding API role to GET /clientsWithKeys in auth process
  packages/authorization-process/src/routers/AuthorizationRouter.ts
Labels: bff, authorization-process

#1056 IMN-872 - Fixing SAML token request
  packages/backend-for-frontend/src/routers/authorizationRouter.ts
  packages/backend-for-frontend/src/routers/supportRouter.ts
  packages/backend-for-frontend/src/services/authorizationService.ts
Labels: bff

#1059 IMN-874: added error to createKeys and createProducerKeychainKey mapper
  packages/authorization-process/src/utilities/errorMappers.ts
  packages/backend-for-frontend/src/routers/clientRouter.ts
Labels: authorization-process

#942 IMN-798 Add events service v2 in catalog-platformstate-writer
  packages/catalog-platformstate-writer/src/consumerServiceV2.ts
  packages/catalog-platformstate-writer/src/utils.ts
  packages/catalog-platformstate-writer/test/consumerServiceV2.test.ts
  packages/catalog-platformstate-writer/test/keys.test.ts
  packages/catalog-platformstate-writer/test/utils.test.ts
  packages/catalog-platformstate-writer/test/utils.ts
  packages/commons-test/package.json
  packages/commons-test/src/index.ts
  packages/commons-test/src/setupDynamoDBtables.ts
  packages/commons-test/src/setupTestContainersVitestGlobal.ts
  packages/commons-test/src/testUtils.ts
  packages/commons-test/src/tokenGenerationReadmodelUtils.ts
  packages/commons/src/config/tokenGenerationReadmodelDbConfig.ts
  packages/models/src/token-generation-readmodel/platform-states-entry.ts
  packages/models/src/token-generation-readmodel/token-generation-states-entry.ts
  pnpm-lock.yaml
Labels: authorization-server

#943 IMN-797 Add events service v1 in catalog-platformstate-writer
  packages/catalog-platformstate-writer/src/consumerServiceV1.ts
  packages/catalog-platformstate-writer/test/consumerServiceV1.test.ts
  packages/catalog-platformstate-writer/test/sample.test.ts
  packages/commons-test/src/testUtils.ts
  packages/models/src/token-generation-readmodel/token-generation-states-entry.ts
Labels: authorization-server

#956 IMN-522 Client-assertion validation
  packages/client-assertion-validation/.env
  packages/client-assertion-validation/package.json
  packages/client-assertion-validation/src/config.ts
  packages/client-assertion-validation/src/errors.ts
  packages/client-assertion-validation/src/index.ts
  packages/client-assertion-validation/src/types.ts
  packages/client-assertion-validation/src/utils.ts
  packages/client-assertion-validation/src/validation.ts
  packages/client-assertion-validation/test/utils.test.ts
  packages/client-assertion-validation/test/utils.ts
  packages/client-assertion-validation/test/validation.test.ts
  packages/client-assertion-validation/test/vitestGlobalSetup.ts
  packages/client-assertion-validation/tsconfig.check.json
  packages/client-assertion-validation/tsconfig.json
  packages/client-assertion-validation/vitest.config.ts
  pnpm-lock.yaml
Labels: authorization-server

#1023 IMN-866 - Tenant quick fixes - fixing some 404 error mappers
  packages/tenant-process/src/utilities/errorMappers.ts
Labels: api-gateway, tenant-process

#962 Verify and revoke verified attribute service fixes
  packages/agreement-process/src/model/domain/apiConverter.ts
  packages/backend-for-frontend/src/api/tenantApiConverter.ts
  packages/models/src/tenant/protobufConverterFromV1.ts
  packages/models/src/tenant/protobufConverterFromV2.ts
  packages/models/src/tenant/tenant.ts
  packages/tenant-process/src/services/tenantService.ts
  packages/tenant-process/test/revokeVerifiedAttribute.test.ts
Labels: tenant-process

#963 IMN 707 - IVASS Certified attributes importer
  .github/workflows/build-push.yaml
  package.json
  packages/ivass-certified-attributes-importer/.env
  packages/ivass-certified-attributes-importer/Dockerfile
  packages/ivass-certified-attributes-importer/README.md
  packages/ivass-certified-attributes-importer/aws.config.local
  packages/ivass-certified-attributes-importer/package.json
  packages/ivass-certified-attributes-importer/src/config/config.ts
  packages/ivass-certified-attributes-importer/src/config/constants.ts
  packages/ivass-certified-attributes-importer/src/index.ts
  packages/ivass-certified-attributes-importer/src/model/csvRowModel.ts
  packages/ivass-certified-attributes-importer/src/model/interopContextModel.ts
  packages/ivass-certified-attributes-importer/src/model/processorModel.ts
  packages/ivass-certified-attributes-importer/src/service/fileDownloader.ts
  packages/ivass-certified-attributes-importer/src/service/processor.ts
  packages/ivass-certified-attributes-importer/src/service/readModelQueriesService.ts
  packages/ivass-certified-attributes-importer/src/service/tenantProcessService.ts
  packages/ivass-certified-attributes-importer/test/helpers.ts
  packages/ivass-certified-attributes-importer/test/processor.test.ts
  packages/ivass-certified-attributes-importer/test/tsconfig.json
  packages/ivass-certified-attributes-importer/test/vitestGlobalSetup.ts
  packages/ivass-certified-attributes-importer/tsconfig.check.json
  packages/ivass-certified-attributes-importer/tsconfig.json
  packages/ivass-certified-attributes-importer/vitest.config.ts
  pnpm-lock.yaml
Labels: interop-be-reports

#1053 Pin 5363 delegation models
  docker/event-store-init.sql
  packages/commons-test/src/eventStoreTestUtils.ts
  packages/commons-test/src/setupTestContainersVitest.ts
  packages/commons-test/src/testUtils.ts
  packages/commons/src/repositories/ReadModelRepository.ts
  packages/models/proto/v2/delegation/delegation.proto
  packages/models/proto/v2/delegation/events.proto
  packages/models/src/brandedIds.ts
  packages/models/src/delegation/delegation.ts
  packages/models/src/delegation/delegationEvents.ts
  packages/models/src/index.ts
Labels: capofila, delegation-process

#1020 IMN-736 - pt 3 - Explicitly handle API GW errors - purpose & tenant
  packages/api-gateway/src/api/purposeApiConverter.ts
  packages/api-gateway/src/clients/catchClientError.ts
  packages/api-gateway/src/models/errors.ts
  packages/api-gateway/src/routers/apiGatewayRouter.ts
  packages/api-gateway/src/services/agreementService.ts
  packages/api-gateway/src/services/purposeService.ts
  packages/api-gateway/src/services/tenantService.ts
  packages/api-gateway/src/services/validators.ts
  packages/api-gateway/src/utilities/errorMappers.ts
Labels: api-gateway

#1042 PIN-5339 - Add multiple users to client and producer keychain
  packages/api-clients/open-api/authorizationApi.yml
  packages/api-clients/open-api/bffApi.yml
  packages/authorization-process/src/routers/AuthorizationRouter.ts
  packages/authorization-process/src/services/authorizationService.ts
  packages/authorization-process/test/addClientUsers.test.ts
  packages/authorization-process/test/addProducerKeychainUsers.test.ts
  packages/backend-for-frontend/src/routers/clientRouter.ts
  packages/backend-for-frontend/src/routers/producerKeychainRouter.ts
  packages/backend-for-frontend/src/services/clientService.ts
  packages/backend-for-frontend/src/services/producerKeychainService.ts
Labels: bff

#1002 Fix jwt token verification skipping invalid WELL_KNOWN_URLS
  packages/agreement-process/src/app.ts
  packages/api-gateway/src/app.ts
  packages/attribute-registry-process/src/app.ts
  packages/authorization-process/src/app.ts
  packages/backend-for-frontend/.env
  packages/backend-for-frontend/src/app.ts
  packages/backend-for-frontend/src/services/authorizationService.ts
  packages/catalog-process/src/app.ts
  packages/commons-test/test/jwt.unit.test.ts
  packages/commons/src/auth/authenticationMiddleware.ts
  packages/commons/src/auth/authorizationMiddleware.ts
  packages/commons/src/auth/headers.ts
  packages/commons/src/auth/jwk.ts
  packages/commons/src/auth/jwt.ts
  packages/commons/src/config/httpServiceConfig.ts
  packages/models/src/errors.ts
  packages/purpose-process/src/app.ts
  packages/tenant-process/src/app.ts
Labels: bff

#1060 PIN-5394 Add delegation process api spec
  packages/api-clients/open-api/delegationApi.yml
Labels: capofila

#1066 PIN-5364 scaffolding delegation process
  .github/workflows/build-push.yaml
  collections/delegation/Delegation Process Micro Service/health/Health status endpoint.bru
  collections/delegation/Delegation Process Micro Service/producer/Approves a delegation.bru
  collections/delegation/Delegation Process Micro Service/producer/Delegation Creation.bru
  collections/delegation/Delegation Process Micro Service/producer/List producer delegations.bru
  collections/delegation/Delegation Process Micro Service/producer/Rejects a delegation.bru
  collections/delegation/Delegation Process Micro Service/producer/Retrieves a delegation.bru
  collections/delegation/Delegation Process Micro Service/producer/Revoke a delegation.bru
  collections/environments/PagoPA local.bru
  package.json
  packages/api-clients/src/index.ts
  packages/delegation-process/.env
  packages/delegation-process/Dockerfile
  packages/delegation-process/package.json
  packages/delegation-process/src/app.ts
  packages/delegation-process/src/config/config.ts
  packages/delegation-process/src/index.ts
  packages/delegation-process/src/routers/DelegationProducerRouter.ts
  packages/delegation-process/src/routers/HealthRouter.ts
  packages/delegation-process/src/services/delegationProducerService.ts
  packages/delegation-process/src/services/readModelService.ts
  packages/delegation-process/test/.eslintrc.json
  packages/delegation-process/test/getDelegationById.test.ts
  packages/delegation-process/test/tsconfig.json
  packages/delegation-process/test/vitestGlobalSetup.ts
  packages/delegation-process/tsconfig.check.json
  packages/delegation-process/tsconfig.json
  packages/delegation-process/vitest.config.ts
  packages/models/src/index.ts
  packages/models/src/read-models/delegationReadModel.ts
  pnpm-lock.yaml
Labels: capofila, delegation-process

#1077 Adding base path to Api Gw
  packages/api-gateway/.env
  packages/api-gateway/src/app.ts
  packages/api-gateway/src/config/config.ts
  packages/backend-for-frontend/src/app.ts
Labels: api-gateway

#1079 IMN-879 - Refactoring headers parsing and improving auth
  packages/api-gateway/src/app.ts
  packages/backend-for-frontend/src/app.ts
  packages/commons/src/auth/authenticationMiddleware.ts
  packages/commons/src/auth/authorizationMiddleware.ts
  packages/commons/src/auth/headers.ts
  packages/commons/src/auth/jwt.ts
  packages/commons/src/context/context.ts
  packages/models/src/errors.ts
Labels: api-gateway, bff

#1055 IMN-858 tenant parsing
  collections/collection.bru
  collections/environments/PagoPA local.bru
  collections/tenant/Add Certified Attribute.bru
  collections/tenant/Add Declared Attribute.bru
  collections/tenant/Add certifier ID to tenant.bru
  collections/tenant/Add tenant mail.bru
  collections/tenant/Consumers.bru
  collections/tenant/Delete tenant mail.bru
  collections/tenant/Delete tenant.bru
  collections/tenant/Internal Assign Certified attribute.bru
  collections/tenant/Internal Revoke Certified attribute.bru
  collections/tenant/Internal upsert tenant.bru
  collections/tenant/Producers.bru
  collections/tenant/Revoke Declared Attribute.bru
  collections/tenant/Revoke certified attribute by id.bru
  collections/tenant/Revoke m2m attribute.bru
  collections/tenant/Revoke verified attribute.bru
  collections/tenant/Status.bru
  collections/tenant/Tenant attributes certified.bru
  collections/tenant/Tenant by Id.bru
  collections/tenant/Tenant by external Id.bru
  collections/tenant/Tenant by selfcare ID.bru
  collections/tenant/Tenants.bru
  collections/tenant/Update verified attribute.bru
  collections/tenant/Upsert selfcare tenant.bru
  collections/tenant/Upsert tenant m2m.bru
  collections/tenant/Verify verified attribute.bru
  packages/tenant-process/src/routers/TenantRouter.ts
Labels: bff-tenant, bff, tenant-process

#976 IMN-616 BFF Tools router
  packages/backend-for-frontend/Dockerfile
  packages/backend-for-frontend/package.json
  packages/backend-for-frontend/src/app.ts
  packages/backend-for-frontend/src/clients/clientsProvider.ts
  packages/backend-for-frontend/src/model/errors.ts
  packages/backend-for-frontend/src/routers/toolRouter.ts
  packages/backend-for-frontend/src/services/toolService.ts
  packages/backend-for-frontend/src/utilities/errorMappers.ts
  packages/client-assertion-validation/src/types.ts
  packages/client-assertion-validation/src/utils.ts
  pnpm-lock.yaml
Labels: bff

#1089 FIX - Client assertion wrong import
  packages/backend-for-frontend/.env
  packages/client-assertion-validation/src/validation.ts
Labels: bff

#1090 IMN-522 Fix check on audience in client-assertion-validation
  packages/client-assertion-validation/.env
  packages/client-assertion-validation/src/config.ts
  packages/client-assertion-validation/src/errors.ts
  packages/client-assertion-validation/src/types.ts
  packages/client-assertion-validation/src/utils.ts
  packages/client-assertion-validation/test/utils.ts
  packages/client-assertion-validation/test/validation.test.ts
Labels: authorization-server

#1078 IMN-861 Add parse in attribute process
  collections/attribute/Create certified attribute (internal).bru
  collections/attribute/Create certified attribute.bru
  collections/attribute/Create declared attribute.bru
  collections/attribute/Create verified attribute.bru
  collections/attribute/Get attribute  by origin code.bru
  collections/attribute/Get attribute by id.bru
  collections/attribute/Get attribute by name.bru
  collections/attribute/Get attributes.bru
  collections/attribute/Get bulk attributes.bru
  collections/environments/PagoPA local.bru
  packages/attribute-registry-process/src/routers/AttributeRouter.ts
Labels: bff, attribute-registry-process

#1065 PIN-5371 - `delegation-readmodel-writer`
  .github/workflows/build-push.yaml
  packages/commons/src/config/kafkaTopicConfig.ts
  packages/delegation-readmodel-writer/.env
  packages/delegation-readmodel-writer/Dockerfile
  packages/delegation-readmodel-writer/kubernetes/dev/configmap.yaml
  packages/delegation-readmodel-writer/kubernetes/dev/deployment.yaml
  packages/delegation-readmodel-writer/kubernetes/dev/serviceAccount.yaml
  packages/delegation-readmodel-writer/package.json
  packages/delegation-readmodel-writer/src/config/config.ts
  packages/delegation-readmodel-writer/src/delegationConsumerServiceV2.ts
  packages/delegation-readmodel-writer/src/index.ts
  packages/delegation-readmodel-writer/test/consumerServiceV2.test.ts
  packages/delegation-readmodel-writer/test/tsconfig.json
  packages/delegation-readmodel-writer/test/utils.ts
  packages/delegation-readmodel-writer/test/vitestGlobalSetup.ts
  packages/delegation-readmodel-writer/tsconfig.check.json
  packages/delegation-readmodel-writer/tsconfig.json
  packages/delegation-readmodel-writer/vitest.config.ts
  packages/models/proto/v2/delegation/delegation.proto
  packages/models/src/delegation/delegationEvents.ts
  packages/models/src/delegation/protobufConverterFromV2.ts
  packages/models/src/delegation/protobufConverterToV2.ts
  packages/models/src/index.ts
  pnpm-lock.yaml
Labels: capofila, delegation-process

#1087 IMN-859 - parse responses in auth process + bruno collection
  collections/authorization/Add Client Purpose.bru
  collections/authorization/Add Client Users.bru
  collections/authorization/Add Producer Keychain Eservice.bru
  collections/authorization/Add Producer Keychain Users.bru
  collections/authorization/Create Api Client.bru
  collections/authorization/Create Client Keys.bru
  collections/authorization/Create Consumer Client.bru
  collections/authorization/Create Producer Keychain Key.bru
  collections/authorization/Create Producer Keychain.bru
  collections/authorization/Delete Client Key.bru
  collections/authorization/Delete Client Purpose.bru
  collections/authorization/Delete Client User.bru
  collections/authorization/Delete Client.bru
  collections/authorization/Delete Producer Keychain Eservice.bru
  collections/authorization/Delete Producer Keychain Key.bru
  collections/authorization/Delete Producer Keychain.bru
  collections/authorization/Delete Purpose from Clients.bru
  collections/authorization/Get Client Key.bru
  collections/authorization/Get Client Keys.bru
  collections/authorization/Get Client Users.bru
  collections/authorization/Get Client.bru
  collections/authorization/Get Clients With Keys.bru
  collections/authorization/Get Clients.bru
  collections/authorization/Get Keys With Client.bru
  collections/authorization/Get Producer Keychain Key.bru
  collections/authorization/Get Producer Keychain Keys.bru
  collections/authorization/Get Producer Keychain Users.bru
  collections/authorization/Get Producer Keychain.bru
  collections/authorization/Get Producer Keychains.bru
  collections/authorization/Remove Producer Keychain User.bru
  collections/authorization/Status.bru
  collections/catalog/Get eservices.bru
  collections/collection.bru
  collections/environments/PagoPA local.bru
  package.json
  packages/authorization-process/src/routers/AuthorizationRouter.ts
Labels: bff, authorization-process

#1091 IMN-882 - API GW bruno collection
  collections/agreement/Get Agreements.bru
  collections/api gateway/agreement/Get Agreement Attributes.bru
  collections/api gateway/agreement/Get Agreement Purposes.bru
  collections/api gateway/agreement/Get Agreement.bru
  collections/api gateway/agreement/Get Agreements.bru
  collections/api gateway/attributes/Create Certified Attribute.bru
  collections/api gateway/attributes/Get Attribute.bru
  collections/api gateway/authorization/Get Client.bru
  collections/api gateway/authorization/Get JWK.bru
  collections/api gateway/catalog/Get Descriptor.bru
  collections/api gateway/catalog/Get Descriptors.bru
  collections/api gateway/catalog/Get Eservice.bru
  collections/api gateway/catalog/Get Eservices.bru
  collections/api gateway/events/Get Agreements Events.bru
  collections/api gateway/events/Get Eservices Events.bru
  collections/api gateway/events/Get Events.bru
  collections/api gateway/events/Get Keys Events.bru
  collections/api gateway/events/Get Producer Keys.bru
  collections/api gateway/purpose/Get Purpose Agreement.bru
  collections/api gateway/purpose/Get Purpose.bru
  collections/api gateway/purpose/Get Purposes.bru
  collections/api gateway/tenant/Get Organization Eservices.bru
  collections/api gateway/tenant/Get Organization.bru
  collections/api gateway/tenant/Revoke Tenant Attribute.bru
  collections/api gateway/tenant/Upsert Tenant.bru
  collections/attribute/Get attribute by id.bru
  collections/environments/PagoPA local.bru
Labels: api-gateway

#1061 PIN-5195 - Assign delegation producer feature route in tenant process
  packages/api-clients/open-api/bffApi.yml
  packages/api-clients/open-api/tenantApi.yml
  packages/attribute-registry-process/src/services/attributeRegistryService.ts
  packages/backend-for-frontend/src/routers/tenantRouter.ts
  packages/backend-for-frontend/src/services/tenantService.ts
  packages/compute-agreements-consumer/src/index.ts
  packages/models/proto/v2/tenant/events.proto
  packages/models/proto/v2/tenant/tenant.proto
  packages/models/src/constants.ts
  packages/models/src/index.ts
  packages/models/src/tenant/protobufConverterFromV2.ts
  packages/models/src/tenant/protobufConverterToV2.ts
  packages/models/src/tenant/tenant.ts
  packages/models/src/tenant/tenantEvents.ts
  packages/tenant-outbound-writer/src/converters/toOutboundEventV2.ts
  packages/tenant-process/src/model/domain/apiConverter.ts
  packages/tenant-process/src/model/domain/errors.ts
  packages/tenant-process/src/model/domain/toEvent.ts
  packages/tenant-process/src/routers/TenantRouter.ts
  packages/tenant-process/src/services/tenantService.ts
  packages/tenant-process/src/services/validators.ts
  packages/tenant-process/src/utilities/errorMappers.ts
  packages/tenant-process/test/assignTenantDelegatedProducerFeature.test.ts
  packages/tenant-readmodel-writer/src/tenantConsumerServiceV2.ts
Labels: tenant-process, capofila

#1058 Pin 5362- BFF delegation api spec and router scaffolding
  packages/api-clients/open-api/bffApi.yml
  packages/backend-for-frontend/src/app.ts
  packages/backend-for-frontend/src/config/config.ts
  packages/backend-for-frontend/src/routers/delegationRouter.ts
  packages/backend-for-frontend/src/routers/producerDelegationRouter.ts
  packages/backend-for-frontend/src/services/delegationService.ts
Labels: capofila

#1106 IMN-888 - /tools/validateTokenGeneration fixes after testing in dev
  packages/backend-for-frontend/src/services/toolService.ts
Labels: bff

#1108 IMN-889 - Using crypto functions instead of jose functions to import keys
  packages/client-assertion-validation/src/validation.ts
  packages/client-assertion-validation/test/keyImport.test.ts
  packages/client-assertion-validation/test/utils.ts
  packages/commons/src/auth/jwk.ts
Labels: bff, authorization-process

#1080 PIN-5365 create producer delegation
  packages/api-clients/open-api/delegationApi.yml
  packages/delegation-process/.env
  packages/delegation-process/src/model/domain/errors.ts
  packages/delegation-process/src/model/domain/models.ts
  packages/delegation-process/src/model/domain/toEvent.ts
  packages/delegation-process/src/routers/DelegationProducerRouter.ts
  packages/delegation-process/src/services/delegationProducerService.ts
  packages/delegation-process/src/services/readModelService.ts
  packages/delegation-process/src/services/validators.ts
  packages/delegation-process/src/utilites/errorMappers.ts
  packages/delegation-process/test/createDelegation.test.ts
  packages/delegation-process/test/getDelegationById.test.ts
  packages/delegation-process/test/getDelegations.test.ts
  packages/delegation-process/test/utils.ts
  packages/models/src/delegation/protobufConverterToV2.ts
Labels: capofila, delegation-process

#1103 PIN-5366 PIN-5367 approve reject
  package.json
  packages/delegation-process/src/model/domain/errors.ts
  packages/delegation-process/src/model/domain/toEvent.ts
  packages/delegation-process/src/routers/DelegationProducerRouter.ts
  packages/delegation-process/src/services/delegationProducerService.ts
  packages/delegation-process/src/services/delegationService.ts
  packages/delegation-process/src/services/readModelService.ts
  packages/delegation-process/src/services/validators.ts
  packages/delegation-process/src/utilites/errorMappers.ts
  packages/delegation-process/test/approveDelegation.test.ts
  packages/delegation-process/test/createDelegation.test.ts
  packages/delegation-process/test/rejectDelegation.test.ts
  packages/delegation-process/test/utils.ts
Labels: capofila, delegation-process

#1038 IMN-800 Add events service v1 in purpose-platformstate-writer
  packages/commons-test/src/index.ts
  packages/commons-test/src/protobufConvertersToV1/purposeProtobufConverterToV1.ts
  packages/purpose-platformstate-writer/src/consumerServiceV1.ts
  packages/purpose-platformstate-writer/src/utils.ts
  packages/purpose-platformstate-writer/test/consumerServiceV1.integration.test.ts
  packages/purpose-readmodel-writer/test/purposeReadmodelWriter.integration.test.ts
Labels: authorization-server

#1121 IMN-898 - Fixing privacy notices S3 path
  docker/minio-seed/privacy-notices-path/0df21ff6-3e8f-4320-af8f-23dea9135d57/65ae113e-e62e-4f68-b79d-5b5659385264/it/privacy-notice.txt
  docker/minio-seed/privacy-notices-path/6bf8412a-41a7-41a0-82dc-26286ce61b1a/0805a4a4-5c7e-4092-96bd-b6dfeda4adfa/it/privacy-notice.txt
  packages/backend-for-frontend/src/services/privacyNoticeService.ts
Labels: bff, privacy-notices

#971 IMN-706 - Porting `dtd-catalog-exporter` job
  packages/dtd-catalog-exporter/.env
  packages/dtd-catalog-exporter/Dockerfile
  packages/dtd-catalog-exporter/README.md
  packages/dtd-catalog-exporter/aws.config.local
  packages/dtd-catalog-exporter/package.json
  packages/dtd-catalog-exporter/src/config/config.ts
  packages/dtd-catalog-exporter/src/index.ts
  packages/dtd-catalog-exporter/src/models/converters.ts
  packages/dtd-catalog-exporter/src/models/models.ts
  packages/dtd-catalog-exporter/src/services/dtdCatalogExporterService.ts
  packages/dtd-catalog-exporter/src/services/readModelService.ts
  packages/dtd-catalog-exporter/src/utils/utils.ts
  packages/dtd-catalog-exporter/test/.eslintrc.json
  packages/dtd-catalog-exporter/test/exportDtdPublicCatalog.test.ts
  packages/dtd-catalog-exporter/test/tsconfig.json
  packages/dtd-catalog-exporter/test/utils.ts
  packages/dtd-catalog-exporter/test/vitestGlobalSetup.ts
  packages/dtd-catalog-exporter/tsconfig.check.json
  packages/dtd-catalog-exporter/tsconfig.json
  packages/dtd-catalog-exporter/vitest.config.ts
  pnpm-lock.yaml
Labels: interop-be-reports

#1100 PIN-5368 Revoke delegation
  packages/delegation-process/src/model/domain/errors.ts
  packages/delegation-process/src/model/domain/toEvent.ts
  packages/delegation-process/src/routers/DelegationProducerRouter.ts
  packages/delegation-process/src/services/delegationProducerService.ts
  packages/delegation-process/src/services/readModelService.ts
  packages/delegation-process/src/services/validators.ts
  packages/delegation-process/src/utilites/errorMappers.ts
  packages/delegation-process/test/approveDelegation.test.ts
  packages/delegation-process/test/createDelegation.test.ts
  packages/delegation-process/test/rejectDelegation.test.ts
  packages/delegation-process/test/revokeDelegation.test.ts
  packages/delegation-process/test/utils.ts
  packages/tenant-process/test/selfcareUpsertTenant.test.ts
Labels: capofila, delegation-process

#1125 IMN-901 - Moving Exact to commons and fixing tenant outbound mapper
  packages/agreement-outbound-writer/src/converters/toOutboundEventV1.ts
  packages/agreement-outbound-writer/src/converters/toOutboundEventV2.ts
  packages/catalog-outbound-writer/src/converters/toOutboundEventV1.ts
  packages/catalog-outbound-writer/src/converters/toOutboundEventV2.ts
  packages/catalog-outbound-writer/src/utils.ts
  packages/commons/src/types/exact.ts
  packages/commons/src/types/index.ts
  packages/purpose-outbound-writer/src/converters/toOutboundEventV1.ts
  packages/purpose-outbound-writer/src/converters/toOutboundEventV2.ts
  packages/purpose-outbound-writer/src/utils.ts
  packages/tenant-outbound-writer/src/converters/toOutboundEventV1.ts
  packages/tenant-outbound-writer/src/converters/toOutboundEventV2.ts
  packages/tenant-outbound-writer/src/utils.ts
Labels: improvement

#1128 IMN-810 - Aligning local dev AWS region with dev env (eu-south-1)
  collections/bff/catalog/Import Eservice.bru
  collections/bff/catalog/Import Eservices.bru
  docker/docker-compose.yml
  packages/agreement-email-sender/.env
  packages/agreement-platformstate-writer/.env
  packages/agreement-process/aws.config.local
  packages/agreement-readmodel-writer/.env
  packages/anac-certified-attributes-importer/aws.config.local
  packages/attribute-registry-readmodel-writer/.env
  packages/authorization-updater/.env
  packages/authorization-updater/aws.config.local
  packages/backend-for-frontend/aws.config.local
  packages/catalog-platformstate-writer/test/utils.test.ts
  packages/catalog-process/aws.config.local
  packages/catalog-readmodel-writer/.env
  packages/client-readmodel-writer/.env
  packages/commons-test/aws.config.local
  packages/commons-test/src/containerTestUtils.ts
  packages/commons-test/test/SES.test.ts
  packages/compute-agreements-consumer/.env
  packages/compute-agreements-consumer/aws.config.local
  packages/datalake-data-export/aws.config.local
  packages/dtd-catalog-exporter/.env
  packages/dtd-catalog-exporter/aws.config.local
  packages/eservice-descriptors-archiver/.env
  packages/eservice-descriptors-archiver/aws.config.local
  packages/ivass-certified-attributes-importer/aws.config.local
  packages/kafka-iam-auth/README.md
  packages/key-readmodel-writer/.env
  packages/notifier-seeder/.env
  packages/notifier-seeder/aws.config.local
  packages/one-trust-notices/aws.config.local
  packages/producer-key-events-writer/.env
  packages/producer-key-readmodel-writer/.env
  packages/producer-keychain-readmodel-writer/.env
  packages/purpose-process/aws.config.local
  packages/purpose-readmodel-writer/.env
  packages/selfcare-onboarding-consumer/.env
  packages/selfcare-onboarding-consumer/aws.config.local
  packages/tenant-readmodel-writer/.env
Labels: improvement

#1129 PIN-5466 document generation on approve
  packages/commons-test/src/testUtils.ts
  packages/commons/src/pdf-generator/pdfGenerator.ts
  packages/delegation-process/.env
  packages/delegation-process/aws.config.local
  packages/delegation-process/package.json
  packages/delegation-process/src/app.ts
  packages/delegation-process/src/config/config.ts
  packages/delegation-process/src/resources/assets/font/Montserrat-Bold.ttf
  packages/delegation-process/src/resources/assets/font/Montserrat-Italic.ttf
  packages/delegation-process/src/resources/assets/font/Montserrat-Medium.ttf
  packages/delegation-process/src/resources/assets/font/Montserrat-Regular.ttf
  packages/delegation-process/src/resources/assets/font/Montserrat-SemiBold.ttf
  packages/delegation-process/src/resources/assets/media/logo_pagopa.png
  packages/delegation-process/src/resources/assets/media/pictogram_pagopa.svg
  packages/delegation-process/src/resources/templates/delegationApprovedTemplate.css
  packages/delegation-process/src/resources/templates/delegationApprovedTemplate.html
  packages/delegation-process/src/routers/DelegationProducerRouter.ts
  packages/delegation-process/src/services/delegationProducerService.ts
  packages/delegation-process/src/services/pdfUtils.ts
  packages/delegation-process/src/utilites/errorMappers.ts
  packages/delegation-process/test/approveDelegation.test.ts
  packages/delegation-process/test/revokeDelegation.test.ts
  packages/delegation-process/test/utils.ts
  pnpm-lock.yaml
Labels: capofila

#1138 Add more checks when verify if delegation exists during creation
  packages/delegation-process/src/model/domain/errors.ts
  packages/delegation-process/src/services/delegationProducerService.ts
  packages/delegation-process/src/services/validators.ts
  packages/delegation-process/test/createDelegation.test.ts
Labels: capofila, delegation-process

#1127 IMN-842 - Removing uuid and using crypto
  packages/agreement-email-sender/package.json
  packages/agreement-outbound-writer/package.json
  packages/agreement-platformstate-writer/package.json
  packages/agreement-process/package.json
  packages/agreement-readmodel-writer/package.json
  packages/anac-certified-attributes-importer/package.json
  packages/attribute-registry-process/package.json
  packages/attribute-registry-process/test/attributeRegistryService.integration.test.ts
  packages/authorization-process/package.json
  packages/authorization-updater/package.json
  packages/backend-for-frontend/package.json
  packages/catalog-outbound-writer/package.json
  packages/catalog-platformstate-writer/package.json
  packages/catalog-process/package.json
  packages/catalog-readmodel-writer/package.json
  packages/client-readmodel-writer/package.json
  packages/commons-test/package.json
  packages/commons/package.json
  packages/commons/src/context/context.ts
  packages/compute-agreements-consumer/package.json
  packages/datalake-data-export/package.json
  packages/eservice-descriptors-archiver/package.json
  packages/ivass-certified-attributes-importer/package.json
  packages/key-readmodel-writer/package.json
  packages/models/package.json
  packages/models/src/brandedIds.ts
  packages/notifier-seeder/package.json
  packages/notifier-seeder/src/models/agreement/agreementEventNotificationMessage.ts
  packages/notifier-seeder/src/models/authorization/authorizationEventNotificationMessage.ts
  packages/notifier-seeder/src/models/catalog/catalogItemEventNotificationMessage.ts
  packages/notifier-seeder/src/models/purpose/purposeEventNotificationMessage.ts
  packages/notifier-seeder/test/notificationMessage.integration.test.ts
  packages/notifier-seeder/test/queueManager.integration.test.ts
  packages/pn-consumers/package.json
  packages/pn-consumers/test/readModelQueriesService.test.ts
  packages/producer-key-events-writer/package.json
  packages/producer-key-readmodel-writer/package.json
  packages/producer-keychain-readmodel-writer/package.json
  packages/purpose-outbound-writer/package.json
  packages/purpose-platformstate-writer/package.json
  packages/purpose-readmodel-writer/package.json
  packages/selfcare-onboarding-consumer/package.json
  packages/tenant-outbound-writer/package.json
  packages/tenant-process/package.json
  pnpm-lock.yaml
Labels: improvement

#987 IMN-792 Add events service v2 in agreement-platformstate-writer
  packages/agreement-platformstate-writer/src/consumerServiceV2.ts
  packages/agreement-platformstate-writer/src/utils.ts
  packages/agreement-platformstate-writer/test/consumerServiceV2.integration.test.ts
  packages/agreement-platformstate-writer/test/utils.test.ts
  packages/agreement-platformstate-writer/test/utils.ts
  packages/catalog-platformstate-writer/test/utils.test.ts
  packages/commons-test/src/testUtils.ts
  packages/commons-test/src/tokenGenerationReadmodelUtils.ts
Labels: authorization-server

#1014 IMN-791 Add events service v1 in agreement-platformstate-writer
  packages/agreement-platformstate-writer/src/consumerServiceV1.ts
  packages/agreement-platformstate-writer/test/agreementPlatformstateWriter.integration.test.ts
  packages/agreement-platformstate-writer/test/consumerServiceV1.integration.test.ts
Labels: authorization-server
