Repository pagopa/interop-be-monorepo, pull requests merged in 2025-06, with the labels that each got.

#1960 Fix bff router
  packages/backend-for-frontend/src/app.ts
Labels: bug

#1910 PIN-6151 : Analytics - Eservice template consumer
  docker/domains-analytics-db/domains-init.sql
  packages/domains-analytics-writer/src/handlers/eservice-template/consumerServiceV2.ts
  packages/domains-analytics-writer/src/index.ts
  packages/domains-analytics-writer/src/model/db/deleting.ts
  packages/domains-analytics-writer/src/model/db/eserviceTemplate.ts
  packages/domains-analytics-writer/src/model/db/index.ts
  packages/domains-analytics-writer/src/model/eserviceTemplate/eserviceTemplate.ts
  packages/domains-analytics-writer/src/model/eserviceTemplate/eserviceTemplateRiskAnalysis.ts
  packages/domains-analytics-writer/src/model/eserviceTemplate/eserviceTemplateRiskAnalysisAnswer.ts
  packages/domains-analytics-writer/src/model/eserviceTemplate/eserviceTemplateVersion.ts
  packages/domains-analytics-writer/src/model/eserviceTemplate/eserviceTemplateVersionAttribute.ts
  packages/domains-analytics-writer/src/model/eserviceTemplate/eserviceTemplateVersionDocument.ts
  packages/domains-analytics-writer/src/model/eserviceTemplate/eserviceTemplateVersionInterface.ts
  packages/domains-analytics-writer/src/repository/eserviceTemplate/eserviceTemplate.repository.ts
  packages/domains-analytics-writer/src/repository/eserviceTemplate/eserviceTemplateRiskAnalysis.repository.ts
  packages/domains-analytics-writer/src/repository/eserviceTemplate/eserviceTemplateRiskAnalysisAnswer.repository.ts
  packages/domains-analytics-writer/src/repository/eserviceTemplate/eserviceTemplateVersion.repository.ts
  packages/domains-analytics-writer/src/repository/eserviceTemplate/eserviceTemplateVersionAttribute.repository.ts
  packages/domains-analytics-writer/src/repository/eserviceTemplate/eserviceTemplateVersionDocument.repository.ts
  packages/domains-analytics-writer/src/repository/eserviceTemplate/eserviceTemplateVersionInterface.repository.ts
  packages/domains-analytics-writer/src/service/eserviceTemplateService.ts
  packages/domains-analytics-writer/test/eserviceTemplate.test.ts
  packages/domains-analytics-writer/test/utils.ts
Labels: kpi

#1972 Fix EServiceDescriptorQuotasUpdatedByTemplateUpdate in catalog-platformstate-writer
  packages/catalog-platformstate-writer/src/consumerServiceV2.ts
  packages/catalog-platformstate-writer/test/consumerServiceV2.test.ts
Labels: authorization-server, eservice-template

#1728 Add getEServiceConsumers test in bff
  packages/backend-for-frontend/test/getEServiceConsumers.test.ts
Labels: bff, mixed-activity

#1731 Test bff exportEServiceDescriptor
  packages/backend-for-frontend/test/exportEServiceDescriptor.test.ts
Labels: bff, mixed-activity

#1949 PIN-6773 - Add expectation on metadata version header where missing in API tests
  packages/delegation-process/test/api/createProducerDelegation.test.ts
  packages/delegation-process/test/api/getDelegationById.test.ts
  packages/delegation-process/test/api/rejectConsumerDelegation.test.ts
  packages/delegation-process/test/api/rejectProducerDelegation.test.ts
Labels: api-v2

#1963 PIN-6735 - adding makeApiProblem unit tests
  packages/commons-test/test/makeApiProblem.unit.test.ts
  packages/models/package.json
  packages/models/src/errors.ts
  pnpm-lock.yaml
Labels: api-v2

#1926 PIN-6924: Analyitics - Consumer batch order execution
  packages/domains-analytics-writer/src/handlers/catalog/consumerServiceV1.ts
  packages/domains-analytics-writer/src/handlers/catalog/consumerServiceV2.ts
  packages/domains-analytics-writer/test/attributesService.test.ts
  packages/domains-analytics-writer/test/catalogService.test.ts
  packages/domains-analytics-writer/test/purposeService.test.ts
Labels: kpi

#1985 PIN-6974: fix for notification-email-sender purpose mails (Including a small improvement on a query)
  packages/authorization-process/src/services/readModelServiceSQL.ts
  packages/notification-email-sender/src/services/notificationEmailSenderService.ts
  packages/notification-email-sender/test/sendNewPurposeVersionWaitingForApprovalEmail.integration.test.ts
  packages/notification-email-sender/test/sendPurposeWaitingForApprovalEmail.integration.test.ts
Labels: bug

#1990 replace RelationshipStatus enum with string in UsersEventPayload
  packages/selfcare-client-users-updater/src/model/UsersEventPayload.ts
  packages/selfcare-client-users-updater/test/selfcareClientUsersUpdaterProcessor.test.ts
Labels: bug, admin-client

#1920 PIN-6916 - Add DPoP validation to token generation
  packages/authorization-server/.env
  packages/authorization-server/package.json
  packages/authorization-server/src/config/config.ts
  packages/authorization-server/src/model/domain/errors.ts
  packages/authorization-server/src/routers/AuthorizationServerRouter.ts
  packages/authorization-server/src/services/tokenService.ts
  packages/authorization-server/src/utilities/errorMappers.ts
  packages/authorization-server/test/api/authorizationServer.api.test.ts
  packages/authorization-server/test/integration/authorizationServer.integration.test.ts
  packages/authorization-server/test/mockUtils.ts
  packages/commons-test/src/setupTestContainersVitestGlobal.ts
  packages/commons-test/src/testConfig.ts
  packages/commons-test/src/testUtils.ts
  packages/commons-test/test/interopTokenService.test.ts
  packages/commons/src/config/dpopConfig.ts
  packages/commons/src/config/index.ts
  packages/commons/src/interop-token/interopTokenService.ts
  packages/dpop-validation/.env.test
  packages/dpop-validation/aws.config.local
  packages/dpop-validation/package.json
  packages/dpop-validation/src/errors.ts
  packages/dpop-validation/src/index.ts
  packages/dpop-validation/src/types.ts
  packages/dpop-validation/src/utilities/dpopCacheUtils.ts
  packages/dpop-validation/src/utilities/utils.ts
  packages/dpop-validation/src/validation.ts
  packages/dpop-validation/test/utils.ts
  packages/dpop-validation/test/validation.test.ts
  packages/dpop-validation/test/vitestGlobalSetup.ts
  packages/dpop-validation/tsconfig.check.json
  packages/dpop-validation/tsconfig.json
  packages/dpop-validation/vitest.config.ts
  pnpm-lock.yaml
Labels: dpop

#1995 Fix e-service risk analysis answers joins
  packages/catalog-process/src/services/readModelServiceSQL.ts
  packages/dtd-catalog-exporter/src/services/readModelServiceSQL.ts
  packages/eservice-template-instances-updater/src/readModelServiceSQL.ts
  packages/readmodel-checker/src/services/readModelServiceSQL.ts
  packages/readmodel/src/catalogReadModelService.ts
  packages/token-generation-readmodel-checker/src/services/readModelServiceSQL.ts
Labels: readmodel-sql, fix-sql

#1979 PIN-6942: Analytics - Catalog consumer (refactor edge cases)
  packages/domains-analytics-writer/src/handlers/catalog/consumerServiceV1.ts
  packages/domains-analytics-writer/src/handlers/catalog/consumerServiceV2.ts
  packages/domains-analytics-writer/src/index.ts
  packages/domains-analytics-writer/src/model/catalog/eserviceDescriptor.ts
  packages/domains-analytics-writer/src/model/catalog/eserviceDescriptorInterface.ts
  packages/domains-analytics-writer/src/model/db/catalog.ts
  packages/domains-analytics-writer/src/model/db/deleting.ts
  packages/domains-analytics-writer/src/model/db/index.ts
  packages/domains-analytics-writer/src/repository/catalog/eservice.repository.ts
  packages/domains-analytics-writer/src/repository/catalog/eserviceDescriptor.repository.ts
  packages/domains-analytics-writer/src/repository/catalog/eserviceDescriptorInterface.repository.ts
  packages/domains-analytics-writer/src/repository/catalog/eserviceRiskAnalysis.repository.ts
  packages/domains-analytics-writer/src/service/catalogService.ts
  packages/domains-analytics-writer/test/catalogService.test.ts
  packages/domains-analytics-writer/test/utils.ts
Labels: kpi

#1997 Fix: Redshift additional predicate in WHEN MATCHED clause error
  packages/domains-analytics-writer/src/utils/sqlQueryHelper.ts
Labels: kpi

#1986 PIN-6939 Analytics - Attribute consumer (refactor edge cases)
  packages/domains-analytics-writer/src/handlers/attribute/consumerServiceV1.ts
  packages/domains-analytics-writer/src/repository/attribute/attribute.repository.ts
  packages/domains-analytics-writer/src/service/attributeService.ts
  packages/domains-analytics-writer/test/attributesService.test.ts
Labels: kpi

#1992 PIN-6977 - M2M get purposes model remap fix
  packages/m2m-gateway/src/api/purposeApiConverter.ts
Labels: api-v2

#2005 Fix JWK in DPoP Proof header
  packages/commons-test/src/testUtils.ts
  packages/dpop-validation/package.json
  packages/dpop-validation/src/errors.ts
  packages/dpop-validation/src/utilities/utils.ts
  packages/dpop-validation/src/validation.ts
  packages/dpop-validation/test/validation.test.ts
  packages/models/src/authorization/key.ts
  pnpm-lock.yaml
Labels: dpop

#1998 PIN-6681 - EService Template `RECEIVE` mode
  docker/domains-analytics-db/domains-init.sql
  docker/readmodel-db/eservice-template.sql
  packages/api-clients/open-api/bffApi.yml
  packages/api-clients/open-api/eserviceTemplateApi.yml
  packages/backend-for-frontend/src/api/eserviceTemplateApiConverter.ts
  packages/backend-for-frontend/src/routers/eserviceTemplateRouter.ts
  packages/backend-for-frontend/src/services/eserviceTemplateService.ts
  packages/catalog-process/src/model/domain/errors.ts
  packages/catalog-process/src/services/catalogService.ts
  packages/catalog-process/src/utilities/errorMappers.ts
  packages/catalog-process/test/api/createEServiceInstanceFromTemplate.test.ts
  packages/catalog-process/test/integration/createEServiceInstanceFromTemplate.test.ts
  packages/commons-test/src/apiMocks.ts
  packages/commons-test/src/riskAnalysisTestUtils.ts
  packages/commons/src/risk-analysis/models.ts
  packages/domains-analytics-writer/test/eserviceTemplate.test.ts
  packages/eservice-template-process/src/model/domain/apiConverter.ts
  packages/eservice-template-process/src/model/domain/errors.ts
  packages/eservice-template-process/src/services/eserviceTemplateService.ts
  packages/eservice-template-process/src/services/readModelService.ts
  packages/eservice-template-process/src/services/validators.ts
  packages/eservice-template-process/src/utilities/errorMappers.ts
  packages/eservice-template-process/test/api/createRiskAnalysis.test.ts
  packages/eservice-template-process/test/api/publishEServiceTemplateVersion.test.ts
  packages/eservice-template-process/test/api/updateRiskAnalysis.test.ts
  packages/eservice-template-process/test/integration/createEServiceTemplateRiskAnalysis.test.ts
  packages/eservice-template-process/test/integration/deleteEServiceTemplateRiskAnalysis.test.ts
  packages/eservice-template-process/test/integration/publishEServiceTemplateVersion.test.ts
  packages/eservice-template-process/test/integration/updateEServiceTemplate.test.ts
  packages/eservice-template-process/test/integration/updateEServiceTemplateRiskAnalysis.test.ts
  packages/eservice-template-process/test/mockUtils.ts
  packages/eservice-template-readmodel-writer-sql/test/eserviceTemplateReadmodelWriter.integration.test.ts
  packages/eservice-template-readmodel-writer/test/eserviceTemplateReadmodelWriter.integration.test.ts
  packages/models/proto/v2/eservice-template/eservice-template.proto
  packages/models/src/eservice-template/eserviceTemplate.ts
  packages/models/src/eservice-template/protobufConverterFromV2.ts
  packages/models/src/eservice-template/protobufConverterToV2.ts
  packages/readmodel-models/src/drizzle/schema.ts
  packages/readmodel/src/catalog/aggregators.ts
  packages/readmodel/src/eservice-template/aggregators.ts
  packages/readmodel/src/eservice-template/splitters.ts
  packages/readmodel/test/eserviceTemplateAggregator.test.ts
  packages/readmodel/test/eserviceTemplateQueries.test.ts
  packages/readmodel/test/eserviceTemplateSplitter.test.ts
Labels: eservice-template

#2009 PIN-7015: Analytics - Authorization producerKeychain (implementation)
  docker/domains-analytics-db/domains-init.sql
  packages/domains-analytics-writer/src/handlers/authorization/consumerServiceV2.ts
  packages/domains-analytics-writer/src/index.ts
  packages/domains-analytics-writer/src/model/authorization/producerKeychain.ts
  packages/domains-analytics-writer/src/model/authorization/producerKeychainEService.ts
  packages/domains-analytics-writer/src/model/authorization/producerKeychainKey.ts
  packages/domains-analytics-writer/src/model/authorization/producerKeychainUser.ts
  packages/domains-analytics-writer/src/model/db/authorization.ts
  packages/domains-analytics-writer/src/model/db/deleting.ts
  packages/domains-analytics-writer/src/model/db/index.ts
  packages/domains-analytics-writer/src/repository/producerKeychain/producerKeychain.repository.ts
  packages/domains-analytics-writer/src/repository/producerKeychain/producerKeychainEService.repository.ts
  packages/domains-analytics-writer/src/repository/producerKeychain/producerKeychainKey.ts
  packages/domains-analytics-writer/src/repository/producerKeychain/producerKeychainUser.repository.ts
  packages/domains-analytics-writer/src/service/authorizationService.ts
  packages/domains-analytics-writer/test/authorizationService.test.ts
  packages/domains-analytics-writer/test/utils.ts
Labels: kpi

#2015 Fix `catalog-platformstate-writer` and `purpose-platformstate-writer` reprocess
  packages/catalog-platformstate-writer/src/consumerServiceV1.ts
  packages/catalog-platformstate-writer/src/consumerServiceV2.ts
  packages/catalog-platformstate-writer/src/utils.ts
  packages/catalog-platformstate-writer/test/consumerServiceV1.test.ts
  packages/catalog-platformstate-writer/test/consumerServiceV2.test.ts
  packages/catalog-platformstate-writer/test/utils.test.ts
  packages/purpose-platformstate-writer/src/consumerServiceV1.ts
  packages/purpose-platformstate-writer/src/consumerServiceV2.ts
  packages/purpose-platformstate-writer/src/utils.ts
  packages/purpose-platformstate-writer/test/consumerServiceV1.integration.test.ts
  packages/purpose-platformstate-writer/test/consumerServiceV2.integration.test.ts
  packages/purpose-platformstate-writer/test/utils.test.ts
Labels: authorization-server

#2021 Add `notYetValidDPoPProof` error to `dpop-validation` + clock offset
  packages/authorization-server/.env
  packages/authorization-server/src/services/tokenService.ts
  packages/authorization-server/test/integration/authorizationServer.integration.test.ts
  packages/authorization-server/test/mockUtils.ts
  packages/commons/src/config/dpopConfig.ts
  packages/dpop-validation/.env.test
  packages/dpop-validation/src/errors.ts
  packages/dpop-validation/src/utilities/dpopCacheUtils.ts
  packages/dpop-validation/src/utilities/utils.ts
  packages/dpop-validation/src/validation.ts
  packages/dpop-validation/test/utils.ts
  packages/dpop-validation/test/validation.test.ts
Labels: dpop

#2030 PIN-7042 - Fix client assertion and DPoP invalid claims logs
  packages/client-assertion-validation/src/errors.ts
  packages/client-assertion-validation/src/validation.ts
  packages/client-assertion-validation/test/validation.test.ts
  packages/dpop-validation/src/errors.ts
  packages/dpop-validation/src/validation.ts
  packages/dpop-validation/test/validation.test.ts
Labels: authorization-server, hotfix

#2037 Analytics: Resolve MERGE deleting statement error
  packages/domains-analytics-writer/src/utils/sqlQueryHelper.ts
Labels: kpi

#2041 PIN-7049 Add correlationId in response header
  packages/commons/src/context/context.ts
Labels: mixed-activity

#1941 PIN-6546 Supertest backend-for-frontend - authorizationRouter, consumerDelegationRouter, eserviceTemplateRouter
  packages/api-clients/open-api/bffApi.yml
  packages/backend-for-frontend/src/services/authorizationService.ts
  packages/backend-for-frontend/test/api/authorizationRouter/getSessionToken.test.ts
  packages/backend-for-frontend/test/api/authorizationRouter/samlLoginCallback.test.ts
  packages/backend-for-frontend/test/api/consumerDelegationRouter/approveConsumerDelegation.test.ts
  packages/backend-for-frontend/test/api/consumerDelegationRouter/createConsumerDelegation.test.ts
  packages/backend-for-frontend/test/api/consumerDelegationRouter/getConsumerDelegatedEservices.test.ts
  packages/backend-for-frontend/test/api/consumerDelegationRouter/getConsumerDelegators.test.ts
  packages/backend-for-frontend/test/api/consumerDelegationRouter/getConsumerDelegatorsWithAgreements.test.ts
  packages/backend-for-frontend/test/api/consumerDelegationRouter/rejectConsumerDelegation.test.ts
  packages/backend-for-frontend/test/api/consumerDelegationRouter/revokeConsumerDelegation.test.ts
  packages/backend-for-frontend/test/api/eserviceTemplateRouter/activateEServiceTemplateVersion.test.ts
  packages/backend-for-frontend/test/api/eserviceTemplateRouter/createEServiceTemplate.test.ts
  packages/backend-for-frontend/test/api/eserviceTemplateRouter/createEServiceTemplateDocument.test.ts
  packages/backend-for-frontend/test/api/eserviceTemplateRouter/createEServiceTemplateEServiceRiskAnalysis.test.ts
  packages/backend-for-frontend/test/api/eserviceTemplateRouter/createEServiceTemplateVersion.test.ts
  packages/backend-for-frontend/test/api/eserviceTemplateRouter/deleteEServiceTemplateDocumentById.test.ts
  packages/backend-for-frontend/test/api/eserviceTemplateRouter/deleteEServiceTemplateEServiceRiskAnalysis.test.ts
  packages/backend-for-frontend/test/api/eserviceTemplateRouter/deleteEServiceTemplateVersion.test.ts
  packages/backend-for-frontend/test/api/eserviceTemplateRouter/getCatalogEServiceTemplates.test.ts
  packages/backend-for-frontend/test/api/eserviceTemplateRouter/getCreatorEServiceTemplates.test.ts
  packages/backend-for-frontend/test/api/eserviceTemplateRouter/getEServiceTemplate.test.ts
  packages/backend-for-frontend/test/api/eserviceTemplateRouter/getEServiceTemplateCreators.test.ts
  packages/backend-for-frontend/test/api/eserviceTemplateRouter/getEServiceTemplateDocument.test.ts
  packages/backend-for-frontend/test/api/eserviceTemplateRouter/getEServiceTemplateVersion.test.ts
  packages/backend-for-frontend/test/api/eserviceTemplateRouter/publishEServiceTemplateVersion.test.ts
  packages/backend-for-frontend/test/api/eserviceTemplateRouter/suspendEServiceTemplateVersion.test.ts
  packages/backend-for-frontend/test/api/eserviceTemplateRouter/updateDraftTemplateVersion.test.ts
  packages/backend-for-frontend/test/api/eserviceTemplateRouter/updateEServiceTemplate.test.ts
  packages/backend-for-frontend/test/api/eserviceTemplateRouter/updateEServiceTemplateDescription.test.ts
  packages/backend-for-frontend/test/api/eserviceTemplateRouter/updateEServiceTemplateDocumentById.test.ts
  packages/backend-for-frontend/test/api/eserviceTemplateRouter/updateEServiceTemplateEServiceRiskAnalysis.test.ts
  packages/backend-for-frontend/test/api/eserviceTemplateRouter/updateEServiceTemplateIntendedTarget.test.ts
  packages/backend-for-frontend/test/api/eserviceTemplateRouter/updateEServiceTemplateName.test.ts
  packages/backend-for-frontend/test/api/eserviceTemplateRouter/updateEServiceTemplateVersionAttributes.test.ts
  packages/backend-for-frontend/test/api/eserviceTemplateRouter/updateEServiceTemplateVersionQuotas.test.ts
  packages/backend-for-frontend/test/mockUtils.ts
  packages/backend-for-frontend/test/vitest.api.setup.ts
Labels: supertest

#1930 Refactor integration test scripts and Turbo pipeline for improved test separation and developer experience
  packages/agreement-process/package.json
  packages/anac-certified-attributes-importer/package.json
  packages/attribute-registry-process/package.json
  packages/authorization-process/package.json
  packages/catalog-process/package.json
  packages/certified-email-sender/package.json
  packages/datalake-data-export/package.json
  packages/delegation-items-archiver/package.json
  packages/delegation-process/package.json
  packages/dtd-catalog-exporter/package.json
  packages/eservice-descriptors-archiver/package.json
  packages/eservice-template-instances-updater/package.json
  packages/eservice-template-process/package.json
  packages/ivass-certified-attributes-importer/package.json
  packages/notification-email-sender/package.json
  packages/pn-consumers/package.json
  packages/purpose-process/package.json
  packages/selfcare-client-users-updater/package.json
  packages/tenant-process/package.json
  packages/token-generation-readmodel-checker/package.json
  turbo.json
Labels: mixed-activity, dx

#2034 Scaffold notification-config-process with one event
  collections/environments/PagoPA local.bru
  collections/notification-config/Update Notification Tenant Configs.bru
  docker/event-store-init.sql
  package.json
  packages/api-clients/open-api/notificationConfigApi.yml
  packages/api-clients/src/index.ts
  packages/commons-test/src/setupTestContainersVitest.ts
  packages/models/proto/v2/notification-config/events.proto
  packages/models/proto/v2/notification-config/notification-config.proto
  packages/models/src/brandedIds.ts
  packages/models/src/index.ts
  packages/models/src/notification-config/notificationConfig.ts
  packages/models/src/notification-config/notificationConfigEvents.ts
  packages/models/src/notification-config/protobufConverterFromV2.ts
  packages/models/src/notification-config/protobufConverterToV2.ts
  packages/models/src/services.ts
  packages/notification-config-process/.env
  packages/notification-config-process/Dockerfile
  packages/notification-config-process/package.json
  packages/notification-config-process/src/app.ts
  packages/notification-config-process/src/config/config.ts
  packages/notification-config-process/src/index.ts
  packages/notification-config-process/src/model/domain/errors.ts
  packages/notification-config-process/src/model/domain/toEvent.ts
  packages/notification-config-process/src/routers/HealthRouter.ts
  packages/notification-config-process/src/routers/NotificationConfigRouter.ts
  packages/notification-config-process/src/services/notificationConfigService.ts
  packages/notification-config-process/test/.eslintrc.json
  packages/notification-config-process/test/api/updateNotificationTenant.test.ts
  packages/notification-config-process/test/integration/updateNotificationTenant.test.ts
  packages/notification-config-process/test/integrationUtils.ts
  packages/notification-config-process/test/vitest.api.setup.ts
  packages/notification-config-process/test/vitestIntegrationGlobalSetup.ts
  packages/notification-config-process/tsconfig.check.json
  packages/notification-config-process/tsconfig.json
  packages/notification-config-process/vitest.api.config.ts
  packages/notification-config-process/vitest.integration.config.ts
  pnpm-lock.yaml
Labels: notification-config

#2039 PIN-7065 - APIV2 `POST /producerDelegations/:delegationId/accept`
  collections/m2m gateway/delegations/Accept producer delegation.bru
  collections/m2m gateway/delegations/Reject producer delegation.bru
  packages/api-clients/open-api/m2mGatewayApi.yml
  packages/delegation-process/src/routers/DelegationRouter.ts
  packages/delegation-process/src/services/delegationService.ts
  packages/delegation-process/test/api/approveProducerDelegation.test.ts
  packages/delegation-process/test/api/rejectProducerDelegation.test.ts
  packages/m2m-gateway/src/routers/delegationRouter.ts
  packages/m2m-gateway/src/services/delegationService.ts
  packages/m2m-gateway/test/api/delegations/acceptProducerDelegation.test.ts
  packages/m2m-gateway/test/api/delegations/rejectProducerDelegation.test.ts
  packages/m2m-gateway/test/integration/delegations/acceptProducerDelegation.test.ts
  packages/m2m-gateway/test/integration/delegations/rejectProducerDelegation.test.ts
Labels: delegation-process, api-v2

#2038 PIN-7064 - APIV2 `GET /producerDelegations`
  collections/m2m gateway/consumerDelegations/folder.bru
  collections/m2m gateway/delegations/Accept consumer delegation.bru
  collections/m2m gateway/delegations/Accept producer delegation.bru
  collections/m2m gateway/delegations/Create consumer delegation.bru
  collections/m2m gateway/delegations/Create producer delegation.bru
  collections/m2m gateway/delegations/List consumer delegations.bru
  collections/m2m gateway/delegations/List producer delegations.bru
  collections/m2m gateway/delegations/Reject consumer delegation.bru
  collections/m2m gateway/delegations/Reject producer delegation.bru
  collections/m2m gateway/delegations/folder.bru
  packages/api-clients/open-api/m2mGatewayApi.yml
  packages/api-clients/src/m2mGatewayApi.ts
  packages/delegation-process/src/routers/DelegationRouter.ts
  packages/delegation-process/src/services/delegationService.ts
  packages/delegation-process/test/api/approveProducerDelegation.test.ts
  packages/delegation-process/test/api/createProducerDelegation.test.ts
  packages/delegation-process/test/api/rejectProducerDelegation.test.ts
  packages/m2m-gateway/src/api/delegationApiConverter.ts
  packages/m2m-gateway/src/routers/delegationRouter.ts
  packages/m2m-gateway/src/services/delegationService.ts
  packages/m2m-gateway/test/api/delegations/acceptConsumerDelegation.test.ts
  packages/m2m-gateway/test/api/delegations/acceptProducerDelegation.test.ts
  packages/m2m-gateway/test/api/delegations/createConsumerDelegation.test.ts
  packages/m2m-gateway/test/api/delegations/createProducerDelegation.test.ts
  packages/m2m-gateway/test/api/delegations/getConsumerDelegations.test.ts
  packages/m2m-gateway/test/api/delegations/getProducerDelegations.test.ts
  packages/m2m-gateway/test/api/delegations/rejectConsumerDelegation.test.ts
  packages/m2m-gateway/test/api/delegations/rejectProducerDelegation.test.ts
  packages/m2m-gateway/test/integration/delegations/acceptConsumerDelegation.test.ts
  packages/m2m-gateway/test/integration/delegations/acceptProducerDelegation.test.ts
  packages/m2m-gateway/test/integration/delegations/createConsumerDelegation.test.ts
  packages/m2m-gateway/test/integration/delegations/createProducerDelegation.test.ts
  packages/m2m-gateway/test/integration/delegations/getConsumerDelegations.test.ts
  packages/m2m-gateway/test/integration/delegations/getProducerDelegations.test.ts
  packages/m2m-gateway/test/integration/delegations/rejectConsumerDelegation.test.ts
  packages/m2m-gateway/test/integration/delegations/rejectProducerDelegation.test.ts
Labels: delegation-process, api-v2

#1947 JWT unit test improvement
  packages/authorization-server/test/api/authorizationServer.api.test.ts
  packages/client-assertion-validation/src/utils.ts
  packages/client-assertion-validation/test/keyImport.test.ts
  packages/client-assertion-validation/test/validation.test.ts
  packages/commons-test/src/mockedPayloadForToken.ts
  packages/commons-test/src/testUtils.ts
  packages/commons-test/test/interopTokenService.test.ts
  packages/commons-test/test/jwt.unit.test.ts
  packages/commons/src/auth/jwt.ts
  packages/commons/src/interop-token/interopTokenService.ts
  packages/commons/src/interop-token/models.ts
  packages/token-details-persister/test/consumerService.integration.test.ts
Labels: refactor

#1744 Added validateTokenGeneration bff test
  packages/backend-for-frontend/test/validateTokenGeneration.test.ts
  packages/commons-test/test/redisRateLimiter.integration.test.ts
Labels: bff, mixed-activity
